"""RCC tasks for the Fizzy Symphony workitem smoke flow."""

from __future__ import annotations

import importlib.util
import json
import os
import re
import shutil
import shlex
import subprocess
import sys
import threading
import time
import types
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

try:
    from robocorp.tasks import get_output_dir, task
except ImportError:  # pragma: no cover - exercised by plain pytest imports.

    def task(func=None, **_kwargs):
        def decorate(target):
            return target

        return decorate(func) if func is not None else decorate

    def get_output_dir() -> str:
        return os.getenv("ROBOT_ARTIFACTS", "output")

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src"
if SRC_ROOT.is_dir() and str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from fizzy_symphony.models import FizzyCard
from fizzy_symphony.robocorp_adapter import (
    RobocorpWorkitemConfig,
    adapter_package_available,
    format_workitem_env,
    initialize_adapter_from_environment,
)
from fizzy_symphony.runners import (
    CodexCliRunner,
    CodexRunResult,
    CodexRunRequest,
    CodexWorkItemRunner,
    create_codex_runner,
)
from fizzy_symphony.workitem_pipeline import CodexWorkItemWorker
from fizzy_symphony.workitem_queue import FizzyWorkItemPayload, JSONDict, WorkItemQueue


WORKAI_SMOKE_ROOT = REPO_ROOT / "test-projects" / "workai-smoke"
WORKAI_FIXTURE_PATH = WORKAI_SMOKE_ROOT / "board.fixture.json"
WORKAI_SAMPLE_PROJECT = WORKAI_SMOKE_ROOT / "sample_project"
PROMPT_CARD_DEFAULT_COLUMNS = [
    "Shaping",
    "Ready for Agents",
    "In Flight",
    "Needs Input",
    "Synthesize & Verify",
    "Ready to Ship",
]
SYMPHONY_AGENT_COLUMN = "Ready for Agents"
SYMPHONY_DONE_COLUMN = "Done"
SYMPHONY_GOLDEN_TAGS = ["agent-instructions", "codex", "move-to-done"]
SYMPHONY_DEFAULT_COLUMNS = [
    "Not Now",
    "Maybe?",
    "Shaping",
    SYMPHONY_AGENT_COLUMN,
    "In Flight",
    "Needs Input",
    "Synthesize & Verify",
    "Ready to Ship",
    SYMPHONY_DONE_COLUMN,
]


class FullSmokeBlocked(RuntimeError):
    """Raised when a production smoke preflight is intentionally not satisfied."""


class InMemoryWorkItemAdapter:
    """Tiny adapter for tests and for safe fallback smoke runs."""

    def __init__(self) -> None:
        self.items: Dict[str, JSONDict] = {}
        self.outputs: Dict[str, JSONDict] = {}
        self.releases: List[Dict[str, Any]] = []
        self.next_id = 1

    def seed_input(self, payload=None, parent_id="", files=None):  # noqa: ARG002
        item_id = f"item-{self.next_id}"
        self.next_id += 1
        self.items[item_id] = dict(payload or {})
        return item_id

    def reserve_input(self):
        return next(iter(self.items))

    def release_input(self, item_id, state, exception=None):
        self.releases.append(
            {
                "item_id": item_id,
                "state": getattr(state, "value", str(state)),
                "exception": exception,
            }
        )
        self.items.pop(item_id, None)

    def create_output(self, parent_id, payload=None):
        output_id = f"output-{len(self.outputs) + 1}"
        self.outputs[output_id] = dict(payload or {})
        return output_id

    def load_payload(self, item_id):
        return dict(self.items[item_id])

    def save_payload(self, item_id, payload):
        self.items[item_id] = dict(payload)


class ContractCodexRunner:
    """Small SDK-shaped runner for robot-level contract tests."""

    runner_kind = "codex_sdk"

    def __call__(self, request: CodexRunRequest) -> CodexRunResult:
        if request.metadata.get("preflight"):
            return CodexRunResult(
                success=True,
                final_response="WORKAI_SDK_PREFLIGHT_OK",
                thread_id="contract-preflight-thread",
                raw_metadata={
                    "runner": "codex_sdk",
                    "thread_id": "contract-preflight-thread",
                    "run_id": "contract-preflight-run",
                    "raw": {"contract": True},
                },
            )

        workspace = Path(str(request.workspace))
        issues_dir = workspace / "contract-issues"
        issues_dir.mkdir(parents=True, exist_ok=True)
        changed_files = []
        for index, title in enumerate(
            [
                "scaffold project command",
                "write smoke proof",
                "document verification",
            ],
            start=1,
        ):
            path = issues_dir / f"contract-issue-{index}.md"
            path.write_text(
                f"# Issue {index}: {title}\n\nGenerated by FizzySymphonyContractTest.\n",
                encoding="utf-8",
            )
            changed_files.append(str(path.relative_to(workspace)))

        plan_path = workspace / "FIZZY_SYMPHONY_CONTRACT_PLAN.md"
        plan_path.write_text(
            "# Fizzy Symphony Contract Plan\n\n"
            "- Created three issue cards as files.\n"
            "- Proved the worker can write artifacts.\n"
            "- Ready for live Fizzy validation.\n",
            encoding="utf-8",
        )
        changed_files.append(plan_path.name)

        return CodexRunResult(
            success=True,
            final_response="Contract runner created three issue artifacts and a proof plan.",
            thread_id="contract-worker-thread",
            artifacts={"changed_files": changed_files},
            validation_summary="contract artifacts written",
            raw_metadata={
                "runner": "codex_sdk",
                "thread_id": "contract-worker-thread",
                "run_id": "contract-worker-run",
                "card_number": request.card_number,
                "raw": {"contract": True, "changed_files": changed_files},
            },
        )


class ParityCodexRunner:
    """SDK-shaped runner for the board-parity robot contract."""

    runner_kind = "codex_sdk"

    def __call__(self, request: CodexRunRequest) -> CodexRunResult:
        if request.metadata.get("preflight"):
            return CodexRunResult(
                success=True,
                final_response="WORKAI_SDK_PREFLIGHT_OK",
                thread_id="parity-preflight-thread",
                raw_metadata={
                    "runner": "codex_sdk",
                    "thread_id": "parity-preflight-thread",
                    "run_id": "parity-preflight-run",
                    "raw": {"parity": True},
                },
            )

        workspace = Path(str(request.workspace))
        proof_path = workspace / "prompt-proof.txt"
        proof_path.write_text(
            "Fizzy Symphony parity contract completed with SDK runner.\n",
            encoding="utf-8",
        )
        return CodexRunResult(
            success=True,
            final_response="Parity runner wrote prompt-proof.txt.",
            thread_id="parity-worker-thread",
            artifacts={"changed_files": ["prompt-proof.txt"]},
            validation_summary="parity proof artifact written",
            raw_metadata={
                "runner": "codex_sdk",
                "thread_id": "parity-worker-thread",
                "run_id": "parity-worker-run",
                "card_number": request.card_number,
                "raw": {"parity": True, "changed_files": ["prompt-proof.txt"]},
            },
        )


def build_synthetic_payload() -> FizzyWorkItemPayload:
    card = FizzyCard(
        id="smoke-card-1",
        number=1,
        identifier="SMOKE-1",
        title="Exercise Fizzy Symphony RCC workitem flow",
        description="Synthetic payload generated by the RCC smoke robot.",
        state="Ready for Agents",
        labels=["rcc", "smoke"],
    )
    return FizzyWorkItemPayload.from_card(
        card,
        board_id="rcc-smoke-board",
        prompt_template="Run a harmless RCC smoke check for {{ card.title }}.",
        allowed_paths=["robots/workitems"],
        handoff_column="Synthesize & Verify",
        runner_command="fake-codex-runner",
    )


def harmless_runner(payload: FizzyWorkItemPayload) -> JSONDict:
    return {
        "success": True,
        "comment": f"Smoke runner completed card {payload.card['number']} without mutation.",
        "handoff_state": payload.workflow["handoff_column"],
        "proof": {
            "runner": "fake",
            "card_id": payload.card["id"],
            "allowed_paths": payload.workflow.get("allowed_paths", []),
        },
    }


def ensure_safe_sqlite_env(output_dir: Path) -> None:
    config = RobocorpWorkitemConfig(
        db_path=str(output_dir / "fizzy-symphony-smoke.db"),
        files_dir=str(output_dir / "workitem-files"),
    )
    for key, value in config.as_env().items():
        os.environ.setdefault(key, value)


def install_adapter_config_shim() -> None:
    """Provide the config hooks expected by robocorp-adapters-custom."""

    if "scripts.config" in sys.modules:
        return

    scripts_module = sys.modules.setdefault("scripts", types.ModuleType("scripts"))
    config_module = types.ModuleType("scripts.config")

    def get_adapter_config() -> Dict[str, str]:
        return {
            "adapter_class": os.environ["RC_WORKITEM_ADAPTER"],
            "db_path": os.environ.get("RC_WORKITEM_DB_PATH", ""),
            "files_dir": os.environ.get("RC_WORKITEM_FILES_DIR", ""),
            "queue_name": os.environ.get("RC_WORKITEM_QUEUE_NAME", ""),
            "output_queue_name": os.environ.get("RC_WORKITEM_OUTPUT_QUEUE_NAME", ""),
        }

    def validate_adapter_config(adapter_class_path: str, config: Dict[str, str]) -> None:
        if "_sqlite" in adapter_class_path:
            missing = [key for key in ("db_path", "files_dir") if not config.get(key)]
            if missing:
                raise ValueError(f"missing SQLite adapter config: {', '.join(missing)}")

    config_module.get_adapter_config = get_adapter_config
    config_module.validate_adapter_config = validate_adapter_config
    scripts_module.config = config_module
    sys.modules["scripts.config"] = config_module


def resolve_output_dir(explicit: Optional[Path] = None) -> Path:
    if explicit is not None:
        path = explicit
    else:
        try:
            path = Path(get_output_dir())
        except Exception:
            path = Path(os.getenv("ROBOT_ARTIFACTS", "output"))
    path.mkdir(parents=True, exist_ok=True)
    return path


def make_smoke_adapter(output_dir: Path, *, prefer_real: bool = True):
    if prefer_real and adapter_package_available():
        ensure_safe_sqlite_env(output_dir)
        install_adapter_config_shim()
        try:
            return initialize_adapter_from_environment(), "robocorp-adapters-custom"
        except RuntimeError:
            raise
        except Exception as exc:
            return InMemoryWorkItemAdapter(), f"in-memory-fallback:{type(exc).__name__}"
    return InMemoryWorkItemAdapter(), "in-memory"


def run_smoke_sqlite_workitem_flow(
    *,
    adapter=None,
    output_dir: Optional[Path] = None,
    prefer_real_adapter: bool = True,
) -> JSONDict:
    artifacts_dir = resolve_output_dir(output_dir)
    selected_adapter, adapter_kind = (
        (adapter, "provided")
        if adapter is not None
        else make_smoke_adapter(artifacts_dir, prefer_real=prefer_real_adapter)
    )
    queue = WorkItemQueue(selected_adapter)

    input_id = queue.enqueue_input(build_synthetic_payload())
    result = CodexWorkItemWorker(queue=queue, runner=harmless_runner).work_one()

    output_payload: JSONDict = {}
    if result.output_id:
        try:
            output_payload = selected_adapter.load_payload(result.output_id)
        except Exception:
            outputs = getattr(selected_adapter, "outputs", {})
            output_payload = outputs.get(result.output_id, {})
    proof: JSONDict = {
        "status": "PASS" if result.succeeded else "FAIL",
        "adapter": adapter_kind,
        "input_id": input_id,
        "worker": {
            "item_id": result.item_id,
            "output_id": result.output_id,
            "succeeded": result.succeeded,
        },
        "output_payload": output_payload,
        "safe_by_default": True,
        "mutated_fizzy": False,
    }

    proof_path = artifacts_dir / "smoke-workitem-flow.json"
    proof_path.write_text(json.dumps(proof, indent=2, sort_keys=True), encoding="utf-8")
    proof["proof_path"] = str(proof_path)
    return proof


def load_workai_fixture(path: Path = WORKAI_FIXTURE_PATH) -> JSONDict:
    return json.loads(path.read_text(encoding="utf-8"))


def run_workai_production_smoke(
    *,
    board_id: Optional[str],
    output_dir: Optional[Path] = None,
    sample_project_dir: Path = WORKAI_SAMPLE_PROJECT,
    fixture_path: Path = WORKAI_FIXTURE_PATH,
    adapter=None,
    runner=None,
    prefer_real_adapter: bool = True,
    live_fizzy: bool = False,
    handoff_column_id: Optional[str] = None,
    live_card_numbers: Optional[Dict[int, int]] = None,
    golden_card_number: Optional[int] = None,
    codex_model: Optional[str] = "gpt-5.4-mini",
    codex_approval_policy: Optional[str] = "never",
    codex_sandbox_mode: Optional[str] = "workspace-write",
) -> JSONDict:
    """Run the WorkAI fixture through SDK-backed workitems and sample tests.

    The default path is intentionally blocked until the public SDK runner exists.
    Tests can inject an SDK-shaped runner to exercise the full harness without
    live Fizzy mutations.
    """

    artifacts_dir = resolve_output_dir(output_dir)
    sample_project_dir = Path(sample_project_dir)
    fixture = load_workai_fixture(fixture_path)
    board_id = _require_disposable_board_id(board_id)
    sdk_runner, sdk_preflight = _require_sdk_runner(
        runner,
        workspace=sample_project_dir,
        codex_model=codex_model,
        codex_approval_policy=codex_approval_policy,
        codex_sandbox_mode=codex_sandbox_mode,
    )
    selected_adapter, adapter_kind = _make_required_workai_adapter(
        artifacts_dir,
        adapter=adapter,
        prefer_real_adapter=prefer_real_adapter,
    )
    queue = WorkItemQueue(selected_adapter)
    setup_commands = _workai_setup_commands(fixture, board_id=board_id)
    fizzy_preflight = _run_fizzy_preflight(
        board_id=board_id,
        fixture=fixture,
        live=live_fizzy,
        live_card_numbers=live_card_numbers,
        golden_card_number=golden_card_number,
    )

    cards = []
    for card in fixture.get("task_cards", []):
        payload = _workai_payload_for_card(
            card,
            board_id=board_id,
            workspace=sample_project_dir,
            codex_model=codex_model,
            codex_approval_policy=codex_approval_policy,
            codex_sandbox_mode=codex_sandbox_mode,
        )
        input_id = queue.enqueue_input(payload)
        worker_result = CodexWorkItemWorker(
            queue=queue,
            runner=CodexWorkItemRunner(sdk_runner),
        ).work_one()
        output_payload = _load_output_payload(selected_adapter, worker_result.output_id)
        fixture_card_number = int(card["number"])
        live_card_number = _resolve_report_card_number(
            fixture_card_number,
            live=live_fizzy,
            live_card_numbers=live_card_numbers,
        )
        report_back = _report_card_result(
            output_payload,
            card_number=live_card_number,
            live=live_fizzy,
            handoff_column_id=handoff_column_id,
        )
        sdk = _sdk_metadata(output_payload.get("result", {}))
        cards.append(
            {
                "card_number": fixture_card_number,
                "live_card_number": live_card_number if live_fizzy else None,
                "title": card["title"],
                "input_id": input_id,
                "worker": {
                    "item_id": worker_result.item_id,
                    "output_id": worker_result.output_id,
                    "succeeded": worker_result.succeeded,
                },
                "sdk": sdk,
                "artifacts": output_payload.get("result", {}).get("artifacts", {}),
                "report_back": report_back,
            }
        )

    sample_tests = _run_sample_project_tests(sample_project_dir, artifacts_dir)
    all_cards_succeeded = all(card["worker"]["succeeded"] for card in cards)
    status = "PASS" if sample_tests["returncode"] == 0 and all_cards_succeeded else "FAIL"
    summary: JSONDict = {
        "status": status,
        "board": {
            "id": board_id,
            "url": _board_url(board_id),
            "mutated_fizzy": live_fizzy,
            "setup_commands": setup_commands,
            "cleanup_command": f"fizzy board delete {shlex.quote(board_id)}",
            "golden_ticket": fixture.get("golden_tickets", [{}])[0].get("title"),
            "golden_proof_command": "fizzy card show <golden card number>",
        },
        "preflight": {
            "fizzy": fizzy_preflight,
            "sqlite_workitems": {
                "adapter": adapter_kind,
                "required": prefer_real_adapter,
            },
            "sdk": sdk_preflight,
        },
        "cards": cards,
        "sample_project_tests": sample_tests,
        "artifacts": {},
    }
    summary_path = artifacts_dir / "workai-production-smoke-summary.json"
    summary["artifacts"]["summary_path"] = str(summary_path)
    summary["artifacts"]["pytest_output_path"] = sample_tests["output_path"]
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    return summary


def run_prompt_card_smoke(
    *,
    board_id: Optional[str],
    card_number: Optional[int],
    prompt: Optional[str],
    workspace: Optional[Path],
    output_dir: Optional[Path] = None,
    adapter=None,
    runner=None,
    prefer_real_adapter: bool = True,
    live_fizzy: bool = False,
    handoff_column_id: Optional[str] = None,
    create_board: bool = False,
    create_card: bool = False,
    board_name: Optional[str] = None,
    card_title: Optional[str] = None,
    codex_model: Optional[str] = "gpt-5.4-mini",
    codex_approval_policy: Optional[str] = "never",
    codex_sandbox_mode: Optional[str] = "workspace-write",
) -> JSONDict:
    """Run one explicit prompt/card through SQLite workitems and Codex SDK."""

    if workspace is None:
        raise FullSmokeBlocked("Prompt card smoke requires FIZZY_SYMPHONY_WORKSPACE.")
    prompt = _require_prompt(prompt)

    artifacts_dir = resolve_output_dir(output_dir)
    workspace = Path(workspace).resolve()
    if not workspace.is_dir():
        raise FullSmokeBlocked(f"Prompt card workspace does not exist: {workspace}")

    bootstrap = _ensure_prompt_board_and_card(
        board_id=board_id,
        card_number=card_number,
        prompt=prompt,
        live=live_fizzy,
        create_board=create_board,
        create_card=create_card,
        board_name=board_name,
        card_title=card_title,
        handoff_column_id=handoff_column_id,
    )
    board_id = str(bootstrap["board_id"])
    card_number = int(bootstrap["card_number"])
    handoff_column_id = handoff_column_id or bootstrap.get("handoff_column_id")

    sdk_runner, sdk_preflight = _require_sdk_runner(
        runner,
        workspace=workspace,
        codex_model=codex_model,
        codex_approval_policy=codex_approval_policy,
        codex_sandbox_mode=codex_sandbox_mode,
    )
    selected_adapter, adapter_kind = _make_required_workai_adapter(
        artifacts_dir,
        adapter=adapter,
        prefer_real_adapter=prefer_real_adapter,
    )
    fizzy_preflight = _run_prompt_card_fizzy_preflight(
        board_id=board_id,
        card_number=card_number,
        live=live_fizzy,
    )

    payload = _prompt_card_payload(
        board_id=board_id,
        card_number=card_number,
        prompt=prompt,
        workspace=workspace,
        live_card=fizzy_preflight.get("card") if live_fizzy else None,
        codex_model=codex_model,
        codex_approval_policy=codex_approval_policy,
        codex_sandbox_mode=codex_sandbox_mode,
    )
    queue = WorkItemQueue(selected_adapter)
    input_id = queue.enqueue_input(payload)
    worker_result = CodexWorkItemWorker(
        queue=queue,
        runner=CodexWorkItemRunner(sdk_runner),
    ).work_one()
    output_payload = _load_output_payload(selected_adapter, worker_result.output_id)
    report_back = _report_card_result(
        output_payload,
        card_number=card_number,
        live=live_fizzy,
        handoff_column_id=handoff_column_id,
    )
    summary: JSONDict = {
        "status": "PASS" if worker_result.succeeded else "FAIL",
        "board": {
            "id": board_id,
            "url": _board_url(board_id),
            "mutated_fizzy": live_fizzy,
            "cleanup_command": bootstrap.get("cleanup_command"),
        },
        "card_number": card_number,
        "workspace": str(workspace),
        "bootstrap": bootstrap,
        "preflight": {
            "fizzy": fizzy_preflight,
            "sqlite_workitems": {"adapter": adapter_kind, "required": prefer_real_adapter},
            "sdk": sdk_preflight,
        },
        "worker": {
            "input_id": input_id,
            "item_id": worker_result.item_id,
            "output_id": worker_result.output_id,
            "succeeded": worker_result.succeeded,
        },
        "sdk": _sdk_metadata(output_payload.get("result", {})),
        "report_back": report_back,
        "artifacts": {},
    }
    summary_path = artifacts_dir / "prompt-card-smoke-summary.json"
    summary["artifacts"]["summary_path"] = str(summary_path)
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    return summary


def run_fizzy_symphony_from_environment(
    *,
    output_dir: Optional[Path] = None,
    adapter=None,
    runner=None,
    prefer_real_adapter: bool = True,
) -> JSONDict:
    artifacts_dir = resolve_output_dir(output_dir)
    board_id = os.getenv("FIZZY_SYMPHONY_BOARD_ID") or None
    card_number = _parse_optional_int(os.getenv("FIZZY_SYMPHONY_CARD_NUMBER"))
    prompt = _prompt_from_environment()
    workspace = _workspace_from_environment(artifacts_dir)
    live_fizzy = _env_bool_default(os.getenv("FIZZY_SYMPHONY_LIVE_FIZZY"), default=True)

    return run_board_native_fizzy_symphony(
        board_id=board_id,
        card_number=card_number,
        prompt=prompt,
        workspace=workspace,
        output_dir=artifacts_dir,
        adapter=adapter,
        runner=runner,
        prefer_real_adapter=prefer_real_adapter,
        live_fizzy=live_fizzy,
        board_name=os.getenv("FIZZY_SYMPHONY_BOARD_NAME") or "Fizzy Symphony",
        card_title=os.getenv("FIZZY_SYMPHONY_CARD_TITLE") or "Run Fizzy Symphony",
        codex_model=os.getenv("FIZZY_SYMPHONY_CODEX_MODEL") or "gpt-5.4-mini",
        codex_approval_policy=os.getenv("FIZZY_SYMPHONY_CODEX_APPROVAL_POLICY") or "never",
        codex_sandbox_mode=os.getenv("FIZZY_SYMPHONY_CODEX_SANDBOX") or "workspace-write",
    )


def run_board_native_fizzy_symphony(
    *,
    board_id: Optional[str],
    card_number: Optional[int],
    prompt: Optional[str],
    workspace: Optional[Path],
    output_dir: Optional[Path] = None,
    adapter=None,
    runner=None,
    prefer_real_adapter: bool = True,
    live_fizzy: bool = False,
    board_name: Optional[str] = None,
    card_title: Optional[str] = None,
    codex_model: Optional[str] = "gpt-5.4-mini",
    codex_approval_policy: Optional[str] = "never",
    codex_sandbox_mode: Optional[str] = "workspace-write",
) -> JSONDict:
    """Run the public board-native Fizzy Symphony path.

    Existing boards are read/discovered only. A missing board id means the
    operator explicitly wants a disposable Symphony board bootstrap.
    """

    if workspace is None:
        raise FullSmokeBlocked("FizzySymphony requires FIZZY_SYMPHONY_WORKSPACE.")

    artifacts_dir = resolve_output_dir(output_dir)
    workspace = Path(workspace).resolve()
    if workspace.exists() and not workspace.is_dir():
        raise FullSmokeBlocked(f"FizzySymphony workspace is not a directory: {workspace}")
    if not workspace.exists():
        workspace.mkdir(parents=True, exist_ok=True)
        print(f"fizzy-symphony workspace_created path={workspace}", flush=True)

    bootstrap = _ensure_symphony_board_and_seed_card(
        board_id=board_id,
        card_number=card_number,
        prompt=prompt,
        live=live_fizzy,
        board_name=board_name,
        card_title=card_title,
    )
    board_id = str(bootstrap["board_id"])

    discovery = _discover_symphony_board(
        board_id,
        live=live_fizzy,
        known_columns=bootstrap.get("columns", {}),
    )
    golden_ticket = _select_golden_ticket(discovery)
    work_cards = _select_work_cards(
        discovery,
        card_number=card_number,
    )
    completion_policy = dict(golden_ticket.get("completion") or {})

    sdk_runner, sdk_preflight = _require_sdk_runner(
        runner,
        workspace=workspace,
        codex_model=codex_model,
        codex_approval_policy=codex_approval_policy,
        codex_sandbox_mode=codex_sandbox_mode,
    )
    selected_adapter, adapter_kind = _make_required_workai_adapter(
        artifacts_dir,
        adapter=adapter,
        prefer_real_adapter=prefer_real_adapter,
    )
    queue = WorkItemQueue(selected_adapter)
    summary_path = artifacts_dir / "fizzy-symphony-summary.json"
    status_path = artifacts_dir / "fizzy-symphony-status.json"

    cards: List[JSONDict] = []
    for work_card in work_cards:
        current_card_number = int(work_card["card_number"])
        assembled_prompt = _assemble_symphony_prompt(
            golden_ticket=golden_ticket,
            work_card=work_card,
            fallback_prompt=prompt,
        )
        fizzy_preflight = _run_prompt_card_fizzy_preflight(
            board_id=board_id,
            card_number=current_card_number,
            live=live_fizzy,
        )
        payload = _prompt_card_payload(
            board_id=board_id,
            card_number=current_card_number,
            prompt=assembled_prompt,
            workspace=workspace,
            live_card=fizzy_preflight.get("card") if live_fizzy else None,
            codex_model=codex_model,
            codex_approval_policy=codex_approval_policy,
            codex_sandbox_mode=codex_sandbox_mode,
        )
        input_id = queue.enqueue_input(payload)
        running_status = _worker_running_status(
            board_id=board_id,
            card_number=current_card_number,
            workspace=workspace,
            input_id=input_id,
            adapter_kind=adapter_kind,
            sdk_preflight=sdk_preflight,
            summary_path=summary_path,
            status_path=status_path,
        )
        _write_fizzy_symphony_progress(status_path, running_status)
        with _worker_heartbeat(status_path, running_status):
            worker_result = CodexWorkItemWorker(
                queue=queue,
                runner=CodexWorkItemRunner(sdk_runner),
            ).work_one()
        output_payload = _load_output_payload(selected_adapter, worker_result.output_id)
        report_back = _report_card_result(
            output_payload,
            card_number=current_card_number,
            live=live_fizzy,
            handoff_column_id=completion_policy.get("column_id"),
            completion_policy=completion_policy,
        )
        cards.append(
            {
                "card_number": current_card_number,
                "title": work_card.get("title") or "",
                "input_id": input_id,
                "preflight": fizzy_preflight,
                "worker": {
                    "item_id": worker_result.item_id,
                    "output_id": worker_result.output_id,
                    "succeeded": worker_result.succeeded,
                },
                "sdk": _sdk_metadata(output_payload.get("result", {})),
                "report_back": report_back,
            }
        )

    first_card = cards[0]
    all_cards_succeeded = all(card["worker"]["succeeded"] for card in cards)
    last_card = cards[-1]
    if cards:
        _write_fizzy_symphony_progress(
            status_path,
            {
                "status": "RUNNING",
                "phase": "reporting_complete",
                "board_id": board_id,
                "card_number": last_card["card_number"],
                "workspace": str(workspace),
                "worker": last_card["worker"],
                "queue": {"adapter": adapter_kind, "state": "COMPLETED"},
                "sdk": last_card["sdk"],
                "summary_path": str(summary_path),
                "status_path": str(status_path),
            },
        )
    report_back = first_card["report_back"]
    card_number = int(first_card["card_number"])
    fizzy_preflight = first_card["preflight"]
    sdk = first_card["sdk"]
    summary: JSONDict = {
        "status": "PASS" if all_cards_succeeded else "FAIL",
        "run_mode": os.getenv("FIZZY_SYMPHONY_RUN_MODE") or "once",
        "board": {
            "id": board_id,
            "url": _board_url(board_id),
            "mutated_fizzy": live_fizzy,
            "cleanup_command": bootstrap.get("cleanup_command"),
        },
        "card_number": card_number,
        "card_numbers": [card["card_number"] for card in cards],
        "cards": cards,
        "workspace": str(workspace),
        "bootstrap": bootstrap,
        "discovery": discovery,
        "preflight": {
            "fizzy": fizzy_preflight,
            "sqlite_workitems": {"adapter": adapter_kind, "required": prefer_real_adapter},
            "sdk": sdk_preflight,
        },
        "worker": first_card["worker"],
        "sdk": sdk,
        "report_back": report_back,
        "artifacts": {},
    }
    summary["artifacts"]["summary_path"] = str(summary_path)
    summary["artifacts"]["status_path"] = str(status_path)
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    _write_fizzy_symphony_status(status_path, summary)
    return summary


def run_fizzy_symphony_contract_test(*, output_dir: Optional[Path] = None) -> JSONDict:
    artifacts_dir = resolve_output_dir(output_dir) / "fizzy-symphony-contract"
    if artifacts_dir.exists():
        shutil.rmtree(artifacts_dir)
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    workspace = artifacts_dir / "workspace"
    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / "README.md").write_text("# Contract Workspace\n", encoding="utf-8")

    env_updates = {
        "FIZZY_SYMPHONY_WORKSPACE": str(workspace),
        "FIZZY_SYMPHONY_PROMPT": (
            "Create a tiny implementation packet with three issue cards and a proof plan."
        ),
        "FIZZY_SYMPHONY_BOARD_ID": "",
        "FIZZY_SYMPHONY_CARD_NUMBER": "",
        "FIZZY_SYMPHONY_HANDOFF_COLUMN_ID": "",
        "FIZZY_SYMPHONY_LIVE_FIZZY": "1",
        "FIZZY_SYMPHONY_CREATE_BOARD": "",
        "FIZZY_SYMPHONY_CREATE_CARD": "",
        "FIZZY_SYMPHONY_BOARD_NAME": "Fizzy Symphony Contract Test",
        "FIZZY_SYMPHONY_CARD_TITLE": "Contract: run multi-issue packet",
    }
    env_backup = {key: os.environ.get(key) for key in env_updates}
    original_run = subprocess.run
    fizzy_calls: List[List[str]] = []
    created_cards: List[JSONDict] = []

    def fake_run(command, *args, **kwargs):  # noqa: ANN001, ANN002, ANN003
        if not command or command[0] != "fizzy":
            return original_run(command, *args, **kwargs)
        fizzy_calls.append([str(part) for part in command])
        stdout = ""
        if command[:2] == ["fizzy", "doctor"]:
            stdout = "ok\n"
        elif command[:3] == ["fizzy", "board", "create"]:
            stdout = json.dumps({"id": "contract_board"})
        elif command[:3] == ["fizzy", "column", "create"]:
            column_name = command[command.index("--name") + 1]
            column_id = f"contract_col_{_slugify(column_name)}"
            stdout = json.dumps({"id": column_id})
        elif command[:3] == ["fizzy", "card", "create"]:
            is_golden = len(created_cards) == 0
            number = 4241 if is_golden else 4242
            title = command[command.index("--title") + 1]
            description = command[command.index("--description") + 1]
            card = {
                "id": "contract_golden" if is_golden else "contract_card",
                "number": number,
                "title": title,
                "description": description,
                "golden": is_golden,
                "tags": ["agent-instructions", "codex", "move-to-done"] if is_golden else [],
                "board": {"id": "contract_board"},
                "column": {
                    "id": "contract_col_ready_for_agents",
                    "name": "Ready for Agents",
                },
            }
            created_cards.append(card)
            stdout = json.dumps({"id": card["id"], "number": number})
        elif command[:3] == ["fizzy", "board", "show"]:
            stdout = json.dumps({"id": "contract_board"})
        elif command[:3] == ["fizzy", "card", "list"]:
            stdout = json.dumps(created_cards)
        elif command[:3] == ["fizzy", "card", "show"]:
            number = int(command[3])
            card = next((card for card in created_cards if card["number"] == number), None)
            if card is None:
                card = {
                    "id": "contract_card",
                    "number": 4242,
                    "title": "Contract: run multi-issue packet",
                    "description": env_updates["FIZZY_SYMPHONY_PROMPT"],
                    "golden": False,
                    "board": {"id": "contract_board"},
                    "column": {
                        "id": "contract_col_ready_for_agents",
                        "name": "Ready for Agents",
                    },
                }
            stdout = json.dumps(
                card
            )
        elif command[:3] in (
            ["fizzy", "card", "golden"],
            ["fizzy", "card", "tag"],
            ["fizzy", "card", "column"],
            ["fizzy", "comment", "create"],
        ):
            stdout = ""
        else:
            return original_run(command, *args, **kwargs)
        return subprocess.CompletedProcess(command, 0, stdout=stdout, stderr="")

    try:
        for key, value in env_updates.items():
            os.environ[key] = value
        subprocess.run = fake_run
        summary = run_fizzy_symphony_from_environment(
            output_dir=artifacts_dir,
            runner=ContractCodexRunner(),
            prefer_real_adapter=True,
        )
    finally:
        subprocess.run = original_run
        for key, value in env_backup.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value

    changed_files = summary.get("sdk", {}).get("raw_metadata", {}).get("raw", {}).get(
        "changed_files", []
    )
    expected_files = [
        "contract-issues/contract-issue-1.md",
        "contract-issues/contract-issue-2.md",
        "contract-issues/contract-issue-3.md",
        "FIZZY_SYMPHONY_CONTRACT_PLAN.md",
    ]
    missing = [path for path in expected_files if not (workspace / path).is_file()]
    if missing:
        raise FullSmokeBlocked(f"Contract test did not create expected artifacts: {missing}")
    if summary.get("status") != "PASS":
        raise FullSmokeBlocked("Contract test summary did not pass.")
    if not summary.get("bootstrap", {}).get("created_board"):
        raise FullSmokeBlocked("Contract test did not create a board.")
    if not summary.get("bootstrap", {}).get("created_card"):
        raise FullSmokeBlocked("Contract test did not create a card.")

    proof = {
        "status": "PASS",
        "summary": summary,
        "workspace": str(workspace),
        "changed_files": changed_files,
        "expected_files": expected_files,
        "fizzy_calls": fizzy_calls,
    }
    proof_path = artifacts_dir / "fizzy-symphony-contract-test.json"
    proof_path.write_text(json.dumps(proof, indent=2, sort_keys=True), encoding="utf-8")
    proof["proof_path"] = str(proof_path)
    return proof


def run_fizzy_symphony_parity_contract(*, output_dir: Optional[Path] = None) -> JSONDict:
    artifacts_dir = resolve_output_dir(output_dir) / "fizzy-symphony-parity-contract"
    if artifacts_dir.exists():
        shutil.rmtree(artifacts_dir)
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    workspace = artifacts_dir / "workspace"
    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / "README.md").write_text("# Fizzy Symphony Parity Workspace\n", encoding="utf-8")

    env_updates = {
        "FIZZY_SYMPHONY_WORKSPACE": str(workspace),
        "FIZZY_SYMPHONY_PROMPT": "Create prompt-proof.txt with a one-line proof.",
        "FIZZY_SYMPHONY_BOARD_ID": "",
        "FIZZY_SYMPHONY_CARD_NUMBER": "",
        "FIZZY_SYMPHONY_LIVE_FIZZY": "1",
        "FIZZY_SYMPHONY_RUN_MODE": "once",
        "FIZZY_SYMPHONY_BOARD_NAME": "Fizzy Symphony Parity Contract",
        "FIZZY_SYMPHONY_CARD_TITLE": "Contract: write prompt proof",
    }
    env_backup = {key: os.environ.get(key) for key in env_updates}
    original_run = subprocess.run
    fizzy_calls: List[List[str]] = []
    created_cards: List[JSONDict] = []

    def fake_run(command, *args, **kwargs):  # noqa: ANN001, ANN002, ANN003
        if not command or command[0] != "fizzy":
            return original_run(command, *args, **kwargs)
        fizzy_calls.append([str(part) for part in command])
        stdout = ""
        if command[:2] == ["fizzy", "doctor"]:
            stdout = "ok\n"
        elif command[:3] == ["fizzy", "board", "create"]:
            stdout = json.dumps({"id": "board_auto"})
        elif command[:3] == ["fizzy", "column", "create"]:
            column_name = command[command.index("--name") + 1]
            stdout = json.dumps({"id": f"col_{_slugify(column_name)}"})
        elif command[:3] == ["fizzy", "card", "create"]:
            is_golden = len(created_cards) == 0
            number = 320 if is_golden else 321
            title = command[command.index("--title") + 1]
            description = command[command.index("--description") + 1]
            card = {
                "id": "card_golden" if is_golden else "card_work",
                "number": number,
                "title": title,
                "description": description,
                "golden": is_golden,
                "tags": ["agent-instructions", "codex", "move-to-done"] if is_golden else [],
                "board": {"id": "board_auto"},
                "column": {"id": "col_ready_for_agents", "name": "Ready for Agents"},
                "steps": ["Read the card", "Write proof", "Report verification"] if is_golden else [],
            }
            created_cards.append(card)
            stdout = json.dumps({"id": card["id"], "number": number})
        elif command[:3] == ["fizzy", "board", "show"]:
            stdout = json.dumps({"id": "board_auto", "name": "Fizzy Symphony Parity Contract"})
        elif command[:3] == ["fizzy", "card", "list"]:
            stdout = json.dumps(created_cards)
        elif command[:3] == ["fizzy", "card", "show"]:
            number = int(command[3])
            card = next((card for card in created_cards if card["number"] == number), None)
            if card is None:
                raise AssertionError(f"unknown fake card number: {number}")
            stdout = json.dumps(card)
        elif command[:3] in (
            ["fizzy", "card", "golden"],
            ["fizzy", "card", "tag"],
            ["fizzy", "card", "column"],
            ["fizzy", "comment", "create"],
        ):
            stdout = ""
        else:
            raise AssertionError(f"unexpected fake Fizzy command: {command}")
        return subprocess.CompletedProcess(command, 0, stdout=stdout, stderr="")

    try:
        for key, value in env_updates.items():
            os.environ[key] = value
        subprocess.run = fake_run
        summary = run_fizzy_symphony_from_environment(
            output_dir=artifacts_dir,
            runner=ParityCodexRunner(),
            prefer_real_adapter=True,
        )
    finally:
        subprocess.run = original_run
        for key, value in env_backup.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value

    if summary.get("status") != "PASS":
        raise FullSmokeBlocked("Parity contract summary did not pass.")
    if not (workspace / "prompt-proof.txt").is_file():
        raise FullSmokeBlocked("Parity contract did not create prompt-proof.txt.")
    if not summary.get("bootstrap", {}).get("golden_ticket_created"):
        raise FullSmokeBlocked("Parity contract did not create a golden ticket.")
    if not summary.get("discovery", {}).get("discovered_golden_ticket"):
        raise FullSmokeBlocked("Parity contract did not discover its golden ticket.")

    proof = {
        "status": "PASS",
        "mutated_fizzy": False,
        "fizzy_boundary": "fake-cli",
        "golden_ticket_created": True,
        "discovered_golden_ticket": True,
        "golden_ticket_number": summary.get("bootstrap", {}).get("golden_ticket_number"),
        "work_card_number": summary.get("bootstrap", {}).get("work_card_number"),
        "card_number": summary.get("card_number"),
        "completion_tag": summary.get("discovery", {})
        .get("golden_tickets", [{}])[0]
        .get("completion", {})
        .get("tag"),
        "summary": summary,
        "workspace": str(workspace),
        "fizzy_calls": fizzy_calls,
    }
    proof_path = artifacts_dir / "fizzy-symphony-parity-contract.json"
    proof_path.write_text(json.dumps(proof, indent=2, sort_keys=True), encoding="utf-8")
    proof["proof_path"] = str(proof_path)
    return proof


def run_fizzy_symphony_status(*, output_dir: Optional[Path] = None) -> JSONDict:
    artifacts_dir = resolve_output_dir(output_dir)
    candidates = [
        artifacts_dir / "fizzy-symphony-status.json",
        artifacts_dir / "fizzy-symphony-summary.json",
        artifacts_dir
        / "fizzy-symphony-parity-contract"
        / "fizzy-symphony-status.json",
    ]
    for path in candidates:
        if path.is_file():
            status = json.loads(path.read_text(encoding="utf-8"))
            status["status_path"] = str(path)
            return status
    return {
        "status": "UNKNOWN",
        "message": "No Fizzy Symphony status artifact found yet.",
        "output_dir": str(artifacts_dir),
    }


def _require_disposable_board_id(board_id: Optional[str]) -> str:
    return _require_board_id(
        board_id,
        "Full WorkAI smoke requires an explicit disposable board id. "
        "Create or choose the disposable board intentionally before running.",
    )


def _require_board_id(board_id: Optional[str], message: str) -> str:
    if not board_id:
        raise FullSmokeBlocked(message)
    return board_id


def _slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def _ensure_symphony_board_and_seed_card(
    *,
    board_id: Optional[str],
    card_number: Optional[int],
    prompt: Optional[str],
    live: bool,
    board_name: Optional[str],
    card_title: Optional[str],
) -> JSONDict:
    bootstrap: JSONDict = {
        "created_board": False,
        "created_card": False,
        "golden_ticket_created": False,
        "columns": {},
    }
    if board_id:
        bootstrap["board_id"] = board_id
        if card_number is not None:
            bootstrap["card_number"] = int(card_number)
            bootstrap["work_card_number"] = int(card_number)
        return bootstrap

    if not live:
        raise FullSmokeBlocked(
            "Bootstrapping a missing Fizzy board requires FIZZY_SYMPHONY_LIVE_FIZZY=1."
        )
    prompt = _require_prompt(prompt)

    created_board = _run_json(
        [
            "fizzy",
            "board",
            "create",
            "--name",
            board_name or "Fizzy Symphony",
            "--agent",
            "--quiet",
        ]
    )
    resolved_board_id = _resource_id(created_board, "fizzy board create")
    column_ids = _create_symphony_board_columns(resolved_board_id)
    ready_column_id = column_ids.get(SYMPHONY_AGENT_COLUMN)
    if not ready_column_id:
        raise FullSmokeBlocked("Bootstrapped board did not create a Ready for Agents column.")

    golden_card = _run_json(
        [
            "fizzy",
            "card",
            "create",
            "--board",
            resolved_board_id,
            "--title",
            "Golden: Codex Agent",
            "--description",
            _default_golden_ticket_prompt(),
            "--agent",
            "--quiet",
        ]
    )
    golden_number = _resource_number(golden_card, "fizzy card create golden ticket")
    subprocess.run(["fizzy", "card", "golden", str(golden_number)], check=True)
    for tag in SYMPHONY_GOLDEN_TAGS:
        subprocess.run(["fizzy", "card", "tag", str(golden_number), "--tag", tag], check=True)
    subprocess.run(
        ["fizzy", "card", "column", str(golden_number), "--column", ready_column_id],
        check=True,
    )

    work_numbers: List[int] = []
    for work_card_spec in _prompt_work_card_specs(prompt, card_title=card_title):
        work_card = _run_json(
            [
                "fizzy",
                "card",
                "create",
                "--board",
                resolved_board_id,
                "--title",
                str(work_card_spec["title"]),
                "--description",
                str(work_card_spec["description"]),
                "--agent",
                "--quiet",
            ]
        )
        work_number = _resource_number(work_card, "fizzy card create work card")
        subprocess.run(
            ["fizzy", "card", "column", str(work_number), "--column", ready_column_id],
            check=True,
        )
        work_numbers.append(int(work_number))

    if not work_numbers:
        raise FullSmokeBlocked("FizzySymphony prompt did not produce any work cards.")

    bootstrap.update(
        {
            "created_board": True,
            "created_card": True,
            "golden_ticket_created": True,
            "board_id": resolved_board_id,
            "card_number": work_numbers[0],
            "work_card_number": work_numbers[0],
            "work_card_numbers": work_numbers,
            "golden_ticket_number": int(golden_number),
            "columns": column_ids,
            "agent_column_id": ready_column_id,
            "handoff_column_id": column_ids.get(SYMPHONY_DONE_COLUMN),
            "cleanup_command": f"fizzy board delete {shlex.quote(resolved_board_id)}",
        }
    )
    return bootstrap


def _prompt_work_card_specs(prompt: str, *, card_title: Optional[str]) -> List[JSONDict]:
    section_pattern = re.compile(
        r"^#{2,6}\s+(?:card|task|agent)\s*:\s*(?P<title>.+?)\s*$",
        re.IGNORECASE | re.MULTILINE,
    )
    matches = list(section_pattern.finditer(prompt))
    if not matches:
        return [
            {
                "title": card_title or _prompt_default_card_title(prompt),
                "description": prompt,
            }
        ]

    cards: List[JSONDict] = []
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(prompt)
        description = prompt[start:end].strip()
        cards.append(
            {
                "title": match.group("title").strip() or f"Run Fizzy Symphony {index + 1}",
                "description": description or prompt,
            }
        )
    return cards


def _prompt_default_card_title(prompt: str) -> str:
    for line in prompt.splitlines():
        value = line.strip()
        if not value:
            continue
        heading = re.match(r"^#+\s+(.+)$", value)
        if heading:
            return heading.group(1).strip()[:120]
        return value[:120]
    return "Run Fizzy Symphony"


def _create_symphony_board_columns(board_id: str) -> Dict[str, str]:
    column_ids: Dict[str, str] = {}
    for column in SYMPHONY_DEFAULT_COLUMNS:
        created = _run_json(
            [
                "fizzy",
                "column",
                "create",
                "--board",
                board_id,
                "--name",
                column,
                "--agent",
                "--quiet",
            ]
        )
        column_ids[column] = _resource_id(created, f"fizzy column create {column}")
    return column_ids


def _default_golden_ticket_prompt() -> str:
    return (
        "Use Codex to complete work cards moved into this column. Read the card title, "
        "description, steps, and discussion; make the smallest useful change in the "
        "workspace; then report concise proof of work back to Fizzy."
    )


def _discover_symphony_board(
    board_id: str,
    *,
    live: bool,
    known_columns: Mapping[str, object],
) -> JSONDict:
    if not live:
        raise FullSmokeBlocked("FizzySymphony discovery requires live Fizzy CLI reads.")

    completed = subprocess.run(["fizzy", "doctor"], text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise FullSmokeBlocked(f"fizzy doctor failed: {completed.stderr or completed.stdout}")

    board = _run_json(["fizzy", "board", "show", board_id, "--agent", "--quiet"])
    if str(board.get("id") or "") != board_id:
        raise FullSmokeBlocked(f"Board {board_id} could not be verified.")

    cards = _run_json_list(
        ["fizzy", "card", "list", "--board", board_id, "--all", "--agent", "--quiet"]
    )
    columns = {str(name): str(value) for name, value in dict(known_columns).items()}
    if cards:
        columns.update(_columns_from_cards(cards))

    golden_tickets: List[JSONDict] = []
    for card in cards:
        if not _is_symphony_golden_ticket(card):
            continue
        column_id = _card_column_id(card)
        column_name = _card_column_name(card)
        tags = _card_tags(card)
        golden_tickets.append(
            {
                "card_number": _card_number(card),
                "title": str(card.get("title") or ""),
                "description": str(card.get("description") or ""),
                "column_id": column_id,
                "column_name": column_name,
                "tags": tags,
                "backend": _backend_from_tags(tags) or "codex",
                "completion": _completion_policy_from_tags(tags, columns),
            }
        )

    if not golden_tickets:
        raise FullSmokeBlocked(
            "No golden ticket found on board. Create a real golden card tagged "
            "agent-instructions plus a backend tag such as codex, then move it into "
            "the column agents should watch."
        )

    agent_columns = {
        str(ticket.get("column_id") or ticket.get("column_name"))
        for ticket in golden_tickets
        if ticket.get("column_id") or ticket.get("column_name")
    }
    work_cards: List[JSONDict] = []
    for card in cards:
        if _is_symphony_golden_ticket(card):
            continue
        card_column_key = _card_column_id(card) or _card_column_name(card)
        if card_column_key not in agent_columns:
            continue
        work_cards.append(_work_card_summary(card))

    return {
        "board_id": board_id,
        "board": board,
        "columns": columns,
        "golden_tickets": golden_tickets,
        "work_cards": work_cards,
        "discovered_golden_ticket": bool(golden_tickets),
    }


def _select_golden_ticket(discovery: JSONDict) -> JSONDict:
    tickets = list(discovery.get("golden_tickets") or [])
    if not tickets:
        raise FullSmokeBlocked("No golden ticket is available for this board.")
    for ticket in tickets:
        if ticket.get("backend") == "codex":
            return dict(ticket)
    return dict(tickets[0])


def _select_work_card(discovery: JSONDict, *, card_number: Optional[int]) -> JSONDict:
    return _select_work_cards(discovery, card_number=card_number)[0]


def _select_work_cards(discovery: JSONDict, *, card_number: Optional[int]) -> List[JSONDict]:
    work_cards = list(discovery.get("work_cards") or [])
    if card_number is not None:
        for card in work_cards:
            if int(card.get("card_number")) == int(card_number):
                return [dict(card)]
        raise FullSmokeBlocked(
            f"Card {card_number} is not in a column configured by a golden ticket."
        )
    if not work_cards:
        raise FullSmokeBlocked("No work cards are waiting in golden-ticket columns.")
    return [dict(card) for card in work_cards]


def _assemble_symphony_prompt(
    *,
    golden_ticket: JSONDict,
    work_card: JSONDict,
    fallback_prompt: Optional[str],
) -> str:
    golden_steps = golden_ticket.get("steps") or []
    work_steps = work_card.get("steps") or []
    return "\n\n".join(
        [
            "You are Fizzy Symphony. A Fizzy board is the dispatch surface.",
            "# Golden Ticket Instructions\n"
            f"Title: {golden_ticket.get('title') or 'Golden Ticket'}\n"
            f"Backend: {golden_ticket.get('backend') or 'codex'}\n"
            f"Completion: {golden_ticket.get('completion', {}).get('tag') or 'comment-only'}\n"
            f"{golden_ticket.get('description') or _default_golden_ticket_prompt()}",
            "# Golden Ticket Steps\n" + _format_steps(golden_steps),
            "# Work Card\n"
            f"Card: {work_card.get('card_number')}\n"
            f"Title: {work_card.get('title') or 'Untitled'}\n"
            f"Description: {work_card.get('description') or fallback_prompt or ''}\n"
            f"Tags: {', '.join(work_card.get('tags') or [])}",
            "# Work Card Steps\n" + _format_steps(work_steps),
            "# Proof Of Work\n"
            "Make the requested change in the workspace. Return concise proof including "
            "files changed, validation performed, and anything blocked.",
        ]
    )


def _format_steps(steps: object) -> str:
    if not isinstance(steps, list) or not steps:
        return "- No steps provided."
    lines = []
    for index, step in enumerate(steps, start=1):
        if isinstance(step, Mapping):
            value = step.get("content") or step.get("title") or step.get("name") or step
        else:
            value = step
        lines.append(f"{index}. {value}")
    return "\n".join(lines)


def _columns_from_cards(cards: List[JSONDict]) -> Dict[str, str]:
    columns: Dict[str, str] = {}
    for card in cards:
        column = card.get("column")
        if not isinstance(column, Mapping):
            continue
        column_name = column.get("name") or column.get("title")
        column_id = column.get("id")
        if column_name and column_id:
            columns[str(column_name)] = str(column_id)
    return columns


def _is_symphony_golden_ticket(card: Mapping[str, object]) -> bool:
    return bool(card.get("golden")) and "agent-instructions" in _card_tags(card)


def _work_card_summary(card: JSONDict) -> JSONDict:
    return {
        "card_number": _card_number(card),
        "id": str(card.get("id") or ""),
        "title": str(card.get("title") or ""),
        "description": str(card.get("description") or ""),
        "column_id": _card_column_id(card),
        "column_name": _card_column_name(card),
        "tags": _card_tags(card),
        "steps": card.get("steps") or [],
    }


def _card_number(card: Mapping[str, object]) -> int:
    value = card.get("number") or card.get("card_number")
    if value is None:
        raise FullSmokeBlocked(f"Fizzy card is missing a number: {card}")
    return int(value)


def _card_column_id(card: Mapping[str, object]) -> str:
    column = card.get("column")
    if isinstance(column, Mapping):
        return str(column.get("id") or "")
    return str(card.get("column_id") or "")


def _card_column_name(card: Mapping[str, object]) -> str:
    column = card.get("column")
    if isinstance(column, Mapping):
        return str(column.get("name") or column.get("title") or "")
    return str(card.get("column_name") or card.get("state") or "")


def _card_tags(card: Mapping[str, object]) -> List[str]:
    raw_tags = card.get("tags") or card.get("labels") or []
    tags: List[str] = []
    if isinstance(raw_tags, list):
        for tag in raw_tags:
            if isinstance(tag, Mapping):
                value = tag.get("name") or tag.get("title") or tag.get("label")
            else:
                value = tag
            if value:
                tags.append(str(value).lstrip("#"))
    return tags


def _backend_from_tags(tags: List[str]) -> Optional[str]:
    for backend in ("codex", "claude", "opencode", "anthropic", "openai", "command"):
        if backend in tags:
            return backend
    return None


def _completion_policy_from_tags(tags: List[str], columns: Mapping[str, str]) -> JSONDict:
    if "close-on-complete" in tags:
        return {"action": "close", "tag": "close-on-complete"}
    for tag in tags:
        if not tag.startswith("move-to-"):
            continue
        column_name = _column_name_from_move_tag(tag)
        column_id = _lookup_column_id(columns, column_name)
        return {
            "action": "move",
            "tag": tag,
            "column_name": column_name,
            "column_id": column_id,
        }
    return {"action": "comment", "tag": "comment-only"}


def _column_name_from_move_tag(tag: str) -> str:
    raw = tag.removeprefix("move-to-").replace("-", " ").strip()
    return " ".join(part.capitalize() for part in raw.split()) or raw


def _lookup_column_id(columns: Mapping[str, str], column_name: str) -> Optional[str]:
    normalized = _slugify(column_name)
    for name, column_id in columns.items():
        if _slugify(str(name)) == normalized:
            return str(column_id)
    return None


def _ensure_prompt_board_and_card(
    *,
    board_id: Optional[str],
    card_number: Optional[int],
    prompt: str,
    live: bool,
    create_board: bool,
    create_card: bool,
    board_name: Optional[str],
    card_title: Optional[str],
    handoff_column_id: Optional[str],
) -> JSONDict:
    if (create_board or create_card) and not live:
        raise FullSmokeBlocked(
            "FIZZY_SYMPHONY_CREATE_BOARD and FIZZY_SYMPHONY_CREATE_CARD require "
            "FIZZY_SYMPHONY_LIVE_FIZZY=1 because they mutate Fizzy."
        )

    bootstrap: JSONDict = {
        "created_board": False,
        "created_card": False,
        "columns": {},
    }
    resolved_board_id = board_id
    resolved_card_number = card_number
    column_ids: Dict[str, str] = {}

    if not resolved_board_id:
        if not create_board:
            raise FullSmokeBlocked(
                "Prompt card smoke requires FIZZY_SYMPHONY_BOARD_ID or "
                "FIZZY_SYMPHONY_CREATE_BOARD=1."
            )
        created_board = _run_json(
            [
                "fizzy",
                "board",
                "create",
                "--name",
                board_name or "Fizzy Symphony Prompt Smoke",
                "--agent",
                "--quiet",
            ]
        )
        resolved_board_id = _resource_id(created_board, "fizzy board create")
        bootstrap["created_board"] = True
        bootstrap["cleanup_command"] = f"fizzy board delete {shlex.quote(resolved_board_id)}"
        column_ids = _create_prompt_card_columns(resolved_board_id)
        bootstrap["columns"] = column_ids

    if not resolved_card_number:
        if not create_card:
            raise FullSmokeBlocked(
                "Prompt card smoke requires FIZZY_SYMPHONY_CARD_NUMBER or "
                "FIZZY_SYMPHONY_CREATE_CARD=1."
            )
        created_card = _run_json(
            [
                "fizzy",
                "card",
                "create",
                "--board",
                resolved_board_id,
                "--title",
                card_title or "Fizzy Symphony prompt run",
                "--description",
                prompt,
                "--agent",
                "--quiet",
            ]
        )
        resolved_card_number = _resource_number(created_card, "fizzy card create")
        bootstrap["created_card"] = True
        ready_column_id = column_ids.get("Ready for Agents")
        if ready_column_id:
            subprocess.run(
                ["fizzy", "card", "column", str(resolved_card_number), "--column", ready_column_id],
                check=True,
            )

    resolved_handoff_column_id = handoff_column_id or column_ids.get("Synthesize & Verify")
    if live and not resolved_handoff_column_id:
        raise FullSmokeBlocked(
            "Live prompt card smoke requires FIZZY_SYMPHONY_HANDOFF_COLUMN_ID unless the "
            "robot created a fresh board with the default Synthesize & Verify column."
        )

    bootstrap["board_id"] = resolved_board_id
    bootstrap["card_number"] = int(resolved_card_number)
    bootstrap["handoff_column_id"] = resolved_handoff_column_id
    return bootstrap


def _create_prompt_card_columns(board_id: str) -> Dict[str, str]:
    column_ids: Dict[str, str] = {}
    for column in PROMPT_CARD_DEFAULT_COLUMNS:
        created = _run_json(
            [
                "fizzy",
                "column",
                "create",
                "--board",
                board_id,
                "--name",
                column,
                "--agent",
                "--quiet",
            ]
        )
        column_ids[column] = _resource_id(created, f"fizzy column create {column}")
    return column_ids


def _resource_id(resource: Mapping[str, object], command_name: str) -> str:
    value = resource.get("id")
    if not value:
        raise FullSmokeBlocked(f"{command_name} did not return an id.")
    return str(value)


def _resource_number(resource: Mapping[str, object], command_name: str) -> int:
    value = resource.get("number")
    if not value:
        raise FullSmokeBlocked(f"{command_name} did not return a card number.")
    return int(value)


def _require_sdk_runner(
    runner,
    *,
    workspace: Path,
    codex_model: Optional[str],
    codex_approval_policy: Optional[str],
    codex_sandbox_mode: Optional[str],
):
    if runner is None:
        try:
            runner = create_codex_runner("sdk")
        except Exception as exc:  # noqa: BLE001 - preserve the runner's reason.
            raise FullSmokeBlocked(f"Codex SDK runner is unavailable: {exc}") from exc

    runner_kind = str(getattr(runner, "runner_kind", "")).lower()
    if isinstance(runner, CodexCliRunner) or runner_kind in {"cli", "codex_cli"}:
        raise FullSmokeBlocked("Full WorkAI smoke must use CodexSdkRunner, not CodexCliRunner.")

    try:
        result = runner(
            CodexRunRequest(
                prompt="Reply exactly: WORKAI_SDK_PREFLIGHT_OK",
                workspace=str(workspace),
                model=codex_model,
                approval_policy=codex_approval_policy,
                sandbox_mode=codex_sandbox_mode,
                timeout_seconds=60,
                metadata={"preflight": True, "smoke": "workai"},
            )
        )
    except Exception as exc:  # noqa: BLE001 - placeholder SDK runner raises RuntimeError.
        raise FullSmokeBlocked(f"Codex SDK runner failed preflight: {exc}") from exc

    if not result.success:
        detail = result.stderr or result.validation_summary or result.final_response
        raise FullSmokeBlocked(
            f"Codex SDK runner preflight returned an unsuccessful result: {detail}"
        )
    if not result.final_response:
        raise FullSmokeBlocked("Codex SDK runner preflight did not return final response text.")

    sdk = _sdk_metadata(result.to_workitem_result())
    if sdk["runner"] == "codex_cli":
        raise FullSmokeBlocked("Codex CLI fallback cannot validate SDK-backed production smoke.")
    if not sdk["thread_id"] or not sdk["run_id"] or not sdk["raw_metadata"]:
        raise FullSmokeBlocked(
            "Codex SDK runner preflight must include thread id, run id, and raw metadata."
        )
    return runner, sdk


def _make_required_workai_adapter(
    output_dir: Path,
    *,
    adapter=None,
    prefer_real_adapter: bool,
):
    if adapter is not None:
        return adapter, "provided"
    if not prefer_real_adapter:
        return make_smoke_adapter(output_dir, prefer_real=False)
    if not adapter_package_available():
        raise FullSmokeBlocked("SQLite workitem adapter package is unavailable.")
    ensure_safe_sqlite_env(output_dir)
    install_adapter_config_shim()
    try:
        return initialize_adapter_from_environment(), "robocorp-adapters-custom"
    except Exception as exc:  # noqa: BLE001 - expose adapter initialization blocker.
        raise FullSmokeBlocked(f"SQLite workitem adapter could not initialize: {exc}") from exc


def _workai_payload_for_card(
    card: JSONDict,
    *,
    board_id: str,
    workspace: Path,
    codex_model: Optional[str],
    codex_approval_policy: Optional[str],
    codex_sandbox_mode: Optional[str],
) -> FizzyWorkItemPayload:
    number = int(card["number"])
    fizzy_card = FizzyCard(
        id=f"workai-smoke-{number}",
        number=number,
        identifier=f"WORKAI-{number}",
        title=str(card["title"]),
        description=str(card["description"]),
        state=str(card.get("target_column") or "Ready for Agents"),
        labels=["workai-smoke", "codex-sdk"],
    )
    card_data = {
        **fizzy_card.__dict__,
        "board_id": board_id,
        "expected_artifact": card.get("expected_artifact"),
    }
    return FizzyWorkItemPayload(
        source="fizzy",
        card=card_data,
        workflow={
            "prompt_template": _workai_prompt(card),
            "allowed_paths": ["test-projects/workai-smoke/sample_project"],
            "handoff_column": "Synthesize & Verify",
            "workspace": str(workspace),
        },
        runner={
            "kind": "codex_sdk",
            "workspace": str(workspace),
            "model": codex_model,
            "approval_policy": codex_approval_policy,
            "sandbox_mode": codex_sandbox_mode,
            "timeout_seconds": 600,
        },
    )


def _prompt_card_payload(
    *,
    board_id: str,
    card_number: int,
    prompt: str,
    workspace: Path,
    live_card: Optional[JSONDict],
    codex_model: Optional[str],
    codex_approval_policy: Optional[str],
    codex_sandbox_mode: Optional[str],
) -> FizzyWorkItemPayload:
    title = "Prompt card"
    description = prompt
    if live_card:
        title = str(live_card.get("title") or title)
        description = str(live_card.get("description") or prompt)
    column = live_card.get("column") if live_card else None
    fizzy_card = FizzyCard(
        id=str(live_card.get("id") if live_card else f"prompt-card-{card_number}"),
        number=card_number,
        identifier=f"FIZZY-{card_number}",
        title=title,
        description=description,
        state=str(column.get("name") if isinstance(column, Mapping) else "Ready for Agents"),
        labels=["prompt-card", "codex-sdk"],
    )
    card_data = {**fizzy_card.__dict__, "board_id": board_id}
    return FizzyWorkItemPayload(
        source="fizzy",
        card=card_data,
        workflow={
            "prompt_template": prompt,
            "allowed_paths": [str(workspace)],
            "handoff_column": "Synthesize & Verify",
            "workspace": str(workspace),
        },
        runner={
            "kind": "codex_sdk",
            "workspace": str(workspace),
            "model": codex_model,
            "approval_policy": codex_approval_policy,
            "sandbox_mode": codex_sandbox_mode,
            "timeout_seconds": 900,
        },
    )


def _workai_prompt(card: JSONDict) -> str:
    return (
        "You are running the disposable WorkAI production smoke fixture.\n"
        f"Card {card['number']}: {card['title']}\n"
        f"Task: {card['description']}\n"
        f"Expected artifact: {card['expected_artifact']}\n"
        "Edit only the sample project, run its tests when useful, and return concise proof."
    )


def _load_output_payload(adapter, output_id: Optional[str]) -> JSONDict:
    if output_id is None:
        return {}
    try:
        return adapter.load_payload(output_id)
    except Exception:
        outputs = getattr(adapter, "outputs", {})
        return dict(outputs.get(output_id, {}))


def _sdk_metadata(result: JSONDict) -> JSONDict:
    raw_metadata = dict(result.get("raw_metadata") or {})
    thread_id = result.get("thread_id") or raw_metadata.get("thread_id")
    run_id = raw_metadata.get("run_id") or raw_metadata.get("response_id") or raw_metadata.get("id")
    runner = (
        raw_metadata.get("runner")
        or raw_metadata.get("runner_kind")
        or raw_metadata.get("kind")
    )
    return {
        "runner": runner,
        "thread_id": thread_id,
        "run_id": run_id,
        "raw_metadata": raw_metadata,
    }


def _run_sample_project_tests(sample_project_dir: Path, output_dir: Path) -> JSONDict:
    env = dict(os.environ)
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = (
        str(sample_project_dir)
        if not existing
        else f"{sample_project_dir}{os.pathsep}{existing}"
    )
    command = [sys.executable, "-m", "pytest", "tests"]
    try:
        completed = subprocess.run(
            command,
            cwd=sample_project_dir,
            env=env,
            text=True,
            capture_output=True,
            timeout=120,
            check=False,
        )
        returncode = completed.returncode
        stdout = completed.stdout
        stderr = completed.stderr
    except subprocess.TimeoutExpired as exc:
        returncode = -1
        stdout = _coerce_process_output(exc.stdout)
        stderr = _coerce_process_output(exc.stderr)
        stderr = f"{stderr}\nTimed out after 120 seconds.".strip()
    output_path = output_dir / "workai-sample-pytest.txt"
    output_path.write_text(
        stdout + ("\n--- stderr ---\n" + stderr if stderr else ""),
        encoding="utf-8",
    )
    return {
        "command": command,
        "cwd": str(sample_project_dir),
        "returncode": returncode,
        "stdout": stdout,
        "stderr": stderr,
        "output_path": str(output_path),
    }


def _report_card_result(
    output_payload: JSONDict,
    *,
    card_number: int,
    live: bool,
    handoff_column_id: Optional[str],
    completion_policy: Optional[Mapping[str, object]] = None,
) -> JSONDict:
    completion = dict(completion_policy or {})
    action = str(completion.get("action") or "move")
    result = output_payload.get("result", {})
    sdk = _sdk_metadata(result)
    final_response = str(
        result.get("final_response") or output_payload.get("comment") or "completed"
    )
    comment = (
        "SDK smoke proof: "
        f"{final_response[:180]} "
        f"(thread={sdk['thread_id']}, run={sdk['run_id']})"
    )
    commands = [
        _join_command(["fizzy", "comment", "create", "--card", str(card_number), "--body", comment])
    ]
    target_column = handoff_column_id or _completion_target_placeholder(completion)
    if action == "move":
        commands.append(
            _join_command(
                ["fizzy", "card", "column", str(card_number), "--column", target_column]
            )
        )
    elif action == "close":
        commands.append(_join_command(["fizzy", "card", "close", str(card_number)]))
    if live:
        if action == "move" and not handoff_column_id:
            raise FullSmokeBlocked(
                "Live reporting requires a destination column id for move-on-complete."
            )
        subprocess.run(
            ["fizzy", "comment", "create", "--card", str(card_number), "--body", comment],
            check=True,
        )
        if action == "move":
            subprocess.run(
                ["fizzy", "card", "column", str(card_number), "--column", handoff_column_id],
                check=True,
            )
        elif action == "close":
            subprocess.run(["fizzy", "card", "close", str(card_number)], check=True)
    return {
        "mode": "live" if live else "dry-run",
        "comment": comment,
        "completion_policy": completion or {"action": action},
        "commands": commands,
    }


def _completion_target_placeholder(completion: Mapping[str, object]) -> str:
    column_name = completion.get("column_name") or "Synthesize & Verify"
    return f"<{column_name} column id>"


def _resolve_report_card_number(
    fixture_card_number: int,
    *,
    live: bool,
    live_card_numbers: Optional[Dict[int, int]],
) -> int:
    if not live:
        return fixture_card_number
    if not live_card_numbers or fixture_card_number not in live_card_numbers:
        raise FullSmokeBlocked(
            f"Live WorkAI smoke requires WORKAI_SMOKE_CARD_NUMBERS to map fixture card {fixture_card_number}."
        )
    return int(live_card_numbers[fixture_card_number])


def _run_fizzy_preflight(
    *,
    board_id: str,
    fixture: JSONDict,
    live: bool,
    live_card_numbers: Optional[Dict[int, int]],
    golden_card_number: Optional[int],
) -> JSONDict:
    if not live:
        return {
            "mode": "dry-run",
            "doctor_command": "fizzy doctor",
            "golden_check": "fizzy card show <golden card number>",
        }
    if not golden_card_number:
        raise FullSmokeBlocked("Live WorkAI smoke requires WORKAI_SMOKE_GOLDEN_CARD_NUMBER.")
    if not live_card_numbers:
        raise FullSmokeBlocked("Live WorkAI smoke requires WORKAI_SMOKE_CARD_NUMBERS.")
    completed = subprocess.run(["fizzy", "doctor"], text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise FullSmokeBlocked(f"fizzy doctor failed: {completed.stderr or completed.stdout}")

    board = _run_json(["fizzy", "board", "show", board_id, "--agent", "--quiet"])
    if str(board.get("id") or "") != board_id:
        raise FullSmokeBlocked(f"Disposable board {board_id} could not be verified.")

    golden = _run_json(["fizzy", "card", "show", str(golden_card_number), "--agent", "--quiet"])
    _verify_live_card_on_board(golden, board_id=board_id, expected_golden=True)

    for card in fixture.get("task_cards", []):
        fixture_number = int(card["number"])
        live_number = live_card_numbers.get(fixture_number)
        if live_number is None:
            raise FullSmokeBlocked(
                f"WORKAI_SMOKE_CARD_NUMBERS is missing fixture card {fixture_number}."
            )
        live_card = _run_json(["fizzy", "card", "show", str(live_number), "--agent", "--quiet"])
        _verify_live_card_on_board(live_card, board_id=board_id, expected_golden=False)

    return {
        "mode": "live",
        "doctor_command": "fizzy doctor",
        "stdout": completed.stdout,
        "stderr": completed.stderr,
        "board_id": board_id,
        "golden_card_number": golden_card_number,
        "verified_card_numbers": dict(sorted(live_card_numbers.items())),
    }


def _run_prompt_card_fizzy_preflight(
    *,
    board_id: str,
    card_number: int,
    live: bool,
) -> JSONDict:
    if not live:
        return {
            "mode": "dry-run",
            "board_check": f"fizzy board show {board_id} --agent --quiet",
            "card_check": f"fizzy card show {card_number} --agent --quiet",
        }
    completed = subprocess.run(["fizzy", "doctor"], text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise FullSmokeBlocked(f"fizzy doctor failed: {completed.stderr or completed.stdout}")
    board = _run_json(["fizzy", "board", "show", board_id, "--agent", "--quiet"])
    if str(board.get("id") or "") != board_id:
        raise FullSmokeBlocked(f"Board {board_id} could not be verified.")
    card = _run_json(["fizzy", "card", "show", str(card_number), "--agent", "--quiet"])
    _verify_live_card_on_board(card, board_id=board_id, expected_golden=False)
    return {
        "mode": "live",
        "doctor_command": "fizzy doctor",
        "board_id": board_id,
        "card_number": card_number,
        "card": card,
    }


def _run_json(command: List[str]) -> JSONDict:
    completed = subprocess.run(command, text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise FullSmokeBlocked(completed.stderr or completed.stdout or f"Command failed: {command}")
    try:
        data = json.loads(completed.stdout or "{}")
    except json.JSONDecodeError as exc:
        raise FullSmokeBlocked(f"Command did not return JSON: {command}") from exc
    if isinstance(data, Mapping) and isinstance(data.get("data"), Mapping):
        return dict(data["data"])
    if isinstance(data, Mapping):
        return dict(data)
    return {}


def _run_json_list(command: List[str]) -> List[JSONDict]:
    completed = subprocess.run(command, text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise FullSmokeBlocked(completed.stderr or completed.stdout or f"Command failed: {command}")
    try:
        data = json.loads(completed.stdout or "[]")
    except json.JSONDecodeError as exc:
        raise FullSmokeBlocked(f"Command did not return JSON: {command}") from exc
    if isinstance(data, Mapping):
        data = data.get("data") or data.get("cards") or []
    if not isinstance(data, list):
        return []
    return [dict(item) for item in data if isinstance(item, Mapping)]


def _write_fizzy_symphony_status(path: Path, summary: JSONDict) -> None:
    status = {
        "status": summary.get("status"),
        "phase": "complete",
        "board_id": summary.get("board", {}).get("id"),
        "card_number": summary.get("card_number"),
        "card_numbers": summary.get("card_numbers", []),
        "golden_tickets": summary.get("discovery", {}).get("golden_tickets", []),
        "work_cards": summary.get("discovery", {}).get("work_cards", []),
        "cards": summary.get("cards", []),
        "worker": summary.get("worker", {}),
        "sdk": summary.get("sdk", {}),
        "summary_path": summary.get("artifacts", {}).get("summary_path"),
    }
    path.write_text(json.dumps(status, indent=2, sort_keys=True), encoding="utf-8")


def _worker_running_status(
    *,
    board_id: str,
    card_number: int,
    workspace: Path,
    input_id: str,
    adapter_kind: str,
    sdk_preflight: JSONDict,
    summary_path: Path,
    status_path: Path,
) -> JSONDict:
    return {
        "status": "RUNNING",
        "phase": "worker_running",
        "board_id": board_id,
        "card_number": card_number,
        "workspace": str(workspace),
        "worker": {
            "input_id": input_id,
            "state": "RESERVED",
        },
        "queue": {
            "adapter": adapter_kind,
            "input_queue": "fizzy_codex_input",
            "state": "RESERVED",
        },
        "sdk": {
            "runner": sdk_preflight.get("runner"),
            "preflight_thread_id": sdk_preflight.get("thread_id"),
            "preflight_run_id": sdk_preflight.get("run_id"),
        },
        "summary_path": str(summary_path),
        "status_path": str(status_path),
    }


def _write_fizzy_symphony_progress(path: Path, status: JSONDict) -> None:
    heartbeat = dict(status)
    heartbeat["heartbeat_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    path.write_text(json.dumps(heartbeat, indent=2, sort_keys=True), encoding="utf-8")
    print(
        "fizzy-symphony "
        f"{heartbeat.get('phase')} card={heartbeat.get('card_number')} "
        f"queue={heartbeat.get('queue', {}).get('state')} status_path={path}",
        flush=True,
    )


class _worker_heartbeat:
    def __init__(self, path: Path, status: JSONDict) -> None:
        self.path = path
        self.status = dict(status)
        self.interval = _heartbeat_interval_seconds()
        self._stop = threading.Event()
        self._thread: Optional[threading.Thread] = None

    def __enter__(self) -> "_worker_heartbeat":
        if self.interval <= 0:
            return self
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        return self

    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=1)

    def _run(self) -> None:
        while not self._stop.wait(self.interval):
            _write_fizzy_symphony_progress(self.path, self.status)


def _heartbeat_interval_seconds() -> float:
    raw = os.getenv("FIZZY_SYMPHONY_HEARTBEAT_SECONDS")
    if raw is None or raw == "":
        return 30.0
    try:
        return max(0.0, float(raw))
    except ValueError:
        return 30.0


def _verify_live_card_on_board(card: JSONDict, *, board_id: str, expected_golden: bool) -> None:
    card_board = card.get("board")
    actual_board_id = card_board.get("id") if isinstance(card_board, Mapping) else None
    if actual_board_id != board_id:
        raise FullSmokeBlocked(
            f"Card {card.get('number')} belongs to board {actual_board_id}, not disposable board {board_id}."
        )
    if bool(card.get("golden")) != expected_golden:
        expected = "golden" if expected_golden else "not golden"
        raise FullSmokeBlocked(f"Card {card.get('number')} is not verified as {expected}.")


def _workai_setup_commands(fixture: JSONDict, *, board_id: str) -> List[str]:
    bootstrap = _load_workai_bootstrap_module()
    commands = list(bootstrap.build_dry_run_commands(fixture, board_id=board_id))
    commands.append(f"fizzy board delete {shlex.quote(board_id)}")
    return commands


def _load_workai_bootstrap_module():
    path = WORKAI_SMOKE_ROOT / "bootstrap_board.py"
    spec = importlib.util.spec_from_file_location("workai_smoke_bootstrap_runtime", path)
    module = importlib.util.module_from_spec(spec)
    if spec.loader is None:
        raise RuntimeError(f"could not load {path}")
    spec.loader.exec_module(module)
    return module


def _board_url(board_id: str) -> str:
    return f"fizzy://board/{board_id}"


def _join_command(parts: List[str]) -> str:
    return " ".join(shlex.quote(part) for part in parts)


def _coerce_process_output(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        return value.decode(errors="replace")
    return str(value)


def _parse_card_number_mapping(raw: Optional[str]) -> Optional[Dict[int, int]]:
    if not raw:
        return None
    mapping: Dict[int, int] = {}
    for pair in raw.split(","):
        if not pair.strip():
            continue
        if "=" not in pair:
            raise FullSmokeBlocked("WORKAI_SMOKE_CARD_NUMBERS must use fixture=live pairs.")
        fixture_number, live_number = pair.split("=", 1)
        mapping[int(fixture_number.strip())] = int(live_number.strip())
    return mapping


def _parse_optional_int(raw: Optional[str]) -> Optional[int]:
    if raw is None or raw == "":
        return None
    return int(raw)


def _parse_optional_path(raw: Optional[str]) -> Optional[Path]:
    if raw is None or raw == "":
        return None
    return Path(raw)


def _env_bool(raw: Optional[str]) -> bool:
    return str(raw or "").strip().lower() in {"1", "true", "yes", "on"}


def _env_bool_default(raw: Optional[str], *, default: bool) -> bool:
    if raw is None or raw == "":
        return default
    return _env_bool(raw)


def _prompt_from_environment() -> Optional[str]:
    prompt = os.getenv("FIZZY_SYMPHONY_PROMPT")
    if prompt:
        return prompt
    if os.getenv("FIZZY_SYMPHONY_PROMPT_FILE"):
        return None
    if _can_prompt_interactively():
        value = _read_interactive_value("Prompt", required=True)
        if value:
            return value
    return None


def _workspace_from_environment(output_dir: Path) -> Path:
    raw_workspace = os.getenv("FIZZY_SYMPHONY_WORKSPACE") or os.getenv(
        "FIZZY_SYMPHONY_REPO_URL"
    )
    if raw_workspace:
        if _looks_like_git_workspace(raw_workspace):
            ref = os.getenv("FIZZY_SYMPHONY_GIT_REF") or os.getenv("FIZZY_SYMPHONY_BRANCH")
            return _clone_git_workspace(raw_workspace, output_dir=output_dir, ref=ref)
        workspace = Path(raw_workspace).expanduser()
        if workspace.is_absolute():
            return workspace
        return (REPO_ROOT / workspace).resolve()
    default = REPO_ROOT
    if _can_prompt_interactively():
        value = _read_interactive_value("Workspace", default=str(default))
        return Path(value or default)
    return default


def _can_prompt_interactively() -> bool:
    try:
        return sys.stdin.isatty()
    except Exception:
        return False


def _read_interactive_value(
    label: str,
    *,
    default: Optional[str] = None,
    required: bool = False,
) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        if not required:
            return ""
        print(f"{label} is required.")


def _looks_like_git_workspace(value: str) -> bool:
    if value.startswith(("https://", "http://", "ssh://", "git@", "file://")):
        return True
    return value.endswith(".git")


def _clone_git_workspace(repo_url: str, *, output_dir: Path, ref: Optional[str]) -> Path:
    workspace_root = output_dir / "workspaces"
    workspace_root.mkdir(parents=True, exist_ok=True)
    destination = workspace_root / _git_workspace_name(repo_url, ref)
    if destination.exists():
        _run_git(["git", "-C", str(destination), "fetch", "--all", "--tags", "--prune"])
    else:
        _run_git(["git", "clone", repo_url, str(destination)])
    if ref:
        _run_git(["git", "-C", str(destination), "checkout", ref])
    return destination


def _git_workspace_name(repo_url: str, ref: Optional[str]) -> str:
    repo_name = repo_url.rstrip("/").rsplit("/", 1)[-1]
    if repo_name.endswith(".git"):
        repo_name = repo_name[:-4]
    suffix = f"-{ref}" if ref else ""
    name = re.sub(r"[^A-Za-z0-9_.-]+", "-", f"{repo_name}{suffix}").strip("-")
    return name or "workspace"


def _run_git(command: List[str]) -> None:
    completed = subprocess.run(command, text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise FullSmokeBlocked(completed.stderr or completed.stdout or f"Git failed: {command}")


def _require_prompt(prompt: Optional[str]) -> str:
    if prompt:
        return prompt
    prompt_file = os.getenv("FIZZY_SYMPHONY_PROMPT_FILE")
    if prompt_file:
        return _read_required_prompt_file(Path(prompt_file))
    default_prompt = _resolve_robot_file(Path("devdata/prompt.md"))
    if default_prompt.is_file():
        return _read_required_prompt_file(default_prompt)
    raise FullSmokeBlocked(
        "Prompt card smoke requires FIZZY_SYMPHONY_PROMPT, "
        "FIZZY_SYMPHONY_PROMPT_FILE, or robots/workitems/devdata/prompt.md."
    )


def _read_required_prompt_file(path: Path) -> str:
    resolved_path = _resolve_robot_file(path)
    if not resolved_path.is_file():
        raise FullSmokeBlocked(f"Prompt file does not exist: {resolved_path}")
    text = resolved_path.read_text(encoding="utf-8").strip()
    if text:
        return text
    raise FullSmokeBlocked(f"Prompt file is empty: {resolved_path}")


def _resolve_robot_file(path: Path) -> Path:
    if path.is_absolute():
        return path
    candidates = [Path.cwd() / path]
    candidates.append(REPO_ROOT / path)
    robot_root = os.getenv("ROBOT_ROOT")
    if robot_root:
        candidates.append(Path(robot_root) / path)
    candidates.append(Path(__file__).resolve().parent / path)
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return candidates[0]


@task
def Doctor() -> None:
    output_dir = resolve_output_dir()
    result = {
        "robot": "fizzy-symphony-workitems",
        "output_dir": str(output_dir),
        "adapter_package_available": adapter_package_available(),
        "safe_by_default": True,
    }
    print(json.dumps(result, indent=2, sort_keys=True))


@task
def WorkitemsEnv() -> None:
    print(format_workitem_env(RobocorpWorkitemConfig()))


@task
def SmokeSQLiteWorkitemFlow() -> None:
    proof = run_smoke_sqlite_workitem_flow()
    print(json.dumps(proof, indent=2, sort_keys=True))


@task
def FizzySymphony() -> None:
    proof = run_fizzy_symphony_from_environment()
    print(json.dumps(proof, indent=2, sort_keys=True))


@task
def RunSymphony() -> None:
    proof = run_fizzy_symphony_from_environment()
    print(json.dumps(proof, indent=2, sort_keys=True))


@task
def WorkAIProductionSmoke() -> None:
    proof = run_workai_production_smoke(
        board_id=os.getenv("WORKAI_SMOKE_BOARD_ID"),
        live_fizzy=_env_bool(os.getenv("WORKAI_SMOKE_LIVE_FIZZY")),
        handoff_column_id=os.getenv("WORKAI_SMOKE_HANDOFF_COLUMN_ID"),
        live_card_numbers=_parse_card_number_mapping(os.getenv("WORKAI_SMOKE_CARD_NUMBERS")),
        golden_card_number=_parse_optional_int(os.getenv("WORKAI_SMOKE_GOLDEN_CARD_NUMBER")),
        codex_model=os.getenv("WORKAI_SMOKE_CODEX_MODEL") or "gpt-5.4-mini",
        codex_approval_policy=os.getenv("WORKAI_SMOKE_CODEX_APPROVAL_POLICY") or "never",
        codex_sandbox_mode=os.getenv("WORKAI_SMOKE_CODEX_SANDBOX") or "workspace-write",
    )
    print(json.dumps(proof, indent=2, sort_keys=True))


@task
def FizzySymphonyContractTest() -> None:
    proof = run_fizzy_symphony_contract_test()
    print(json.dumps(proof, indent=2, sort_keys=True))


@task
def FizzySymphonyParityContract() -> None:
    proof = run_fizzy_symphony_parity_contract()
    print(json.dumps(proof, indent=2, sort_keys=True))


@task
def FizzySymphonyStatus() -> None:
    proof = run_fizzy_symphony_status()
    print(json.dumps(proof, indent=2, sort_keys=True))


@task
def PromptCardSmoke() -> None:
    proof = run_fizzy_symphony_from_environment()
    print(json.dumps(proof, indent=2, sort_keys=True))
