"""RCC tasks for the Fizzy Symphony workitem smoke flow."""

from __future__ import annotations

import json
import os
import sys
import types
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    from robocorp.tasks import get_output_dir, task
except ImportError:  # pragma: no cover - exercised by plain pytest imports.

    def task(func=None, **_kwargs):
        def decorate(target):
            return target

        return decorate(func) if func is not None else decorate

    def get_output_dir() -> str:
        return os.getenv("ROBOT_ARTIFACTS", "output")

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src"
if SRC_ROOT.is_dir() and str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from fizzy_symphony.models import FizzyCard
from fizzy_symphony.robocorp_adapter import (
    RobocorpWorkitemConfig,
    adapter_package_available,
    format_workitem_env,
    initialize_adapter_from_environment,
)
from fizzy_symphony.workitem_pipeline import CodexWorkItemWorker
from fizzy_symphony.workitem_queue import FizzyWorkItemPayload, JSONDict, WorkItemQueue


class InMemoryWorkItemAdapter:
    """Tiny adapter for tests and for safe fallback smoke runs."""

    def __init__(self) -> None:
        self.items: Dict[str, JSONDict] = {}
        self.outputs: Dict[str, JSONDict] = {}
        self.releases: List[Dict[str, Any]] = []
        self.next_id = 1

    def seed_input(self, payload=None, parent_id="", files=None):  # noqa: ARG002
        item_id = f"item-{self.next_id}"
        self.next_id += 1
        self.items[item_id] = dict(payload or {})
        return item_id

    def reserve_input(self):
        return next(iter(self.items))

    def release_input(self, item_id, state, exception=None):
        self.releases.append(
            {
                "item_id": item_id,
                "state": getattr(state, "value", str(state)),
                "exception": exception,
            }
        )
        self.items.pop(item_id, None)

    def create_output(self, parent_id, payload=None):
        output_id = f"output-{len(self.outputs) + 1}"
        self.outputs[output_id] = dict(payload or {})
        return output_id

    def load_payload(self, item_id):
        return dict(self.items[item_id])

    def save_payload(self, item_id, payload):
        self.items[item_id] = dict(payload)


def build_synthetic_payload() -> FizzyWorkItemPayload:
    card = FizzyCard(
        id="smoke-card-1",
        number=1,
        identifier="SMOKE-1",
        title="Exercise Fizzy Symphony RCC workitem flow",
        description="Synthetic payload generated by the RCC smoke robot.",
        state="Ready for Agents",
        labels=["rcc", "smoke"],
    )
    return FizzyWorkItemPayload.from_card(
        card,
        board_id="rcc-smoke-board",
        prompt_template="Run a harmless RCC smoke check for {{ card.title }}.",
        allowed_paths=["robots/workitems"],
        handoff_column="Synthesize & Verify",
        runner_command="fake-codex-runner",
    )


def harmless_runner(payload: FizzyWorkItemPayload) -> JSONDict:
    return {
        "success": True,
        "comment": f"Smoke runner completed card {payload.card['number']} without mutation.",
        "handoff_state": payload.workflow["handoff_column"],
        "proof": {
            "runner": "fake",
            "card_id": payload.card["id"],
            "allowed_paths": payload.workflow.get("allowed_paths", []),
        },
    }


def ensure_safe_sqlite_env(output_dir: Path) -> None:
    config = RobocorpWorkitemConfig(
        db_path=str(output_dir / "fizzy-symphony-smoke.db"),
        files_dir=str(output_dir / "workitem-files"),
    )
    for key, value in config.as_env().items():
        os.environ.setdefault(key, value)


def install_adapter_config_shim() -> None:
    """Provide the config hooks expected by robocorp-adapters-custom."""

    if "scripts.config" in sys.modules:
        return

    scripts_module = sys.modules.setdefault("scripts", types.ModuleType("scripts"))
    config_module = types.ModuleType("scripts.config")

    def get_adapter_config() -> Dict[str, str]:
        return {
            "adapter_class": os.environ["RC_WORKITEM_ADAPTER"],
            "db_path": os.environ.get("RC_WORKITEM_DB_PATH", ""),
            "files_dir": os.environ.get("RC_WORKITEM_FILES_DIR", ""),
            "queue_name": os.environ.get("RC_WORKITEM_QUEUE_NAME", ""),
            "output_queue_name": os.environ.get("RC_WORKITEM_OUTPUT_QUEUE_NAME", ""),
        }

    def validate_adapter_config(adapter_class_path: str, config: Dict[str, str]) -> None:
        if "_sqlite" in adapter_class_path:
            missing = [key for key in ("db_path", "files_dir") if not config.get(key)]
            if missing:
                raise ValueError(f"missing SQLite adapter config: {', '.join(missing)}")

    config_module.get_adapter_config = get_adapter_config
    config_module.validate_adapter_config = validate_adapter_config
    scripts_module.config = config_module
    sys.modules["scripts.config"] = config_module


def resolve_output_dir(explicit: Optional[Path] = None) -> Path:
    path = explicit or Path(get_output_dir())
    path.mkdir(parents=True, exist_ok=True)
    return path


def make_smoke_adapter(output_dir: Path, *, prefer_real: bool = True):
    if prefer_real and adapter_package_available():
        ensure_safe_sqlite_env(output_dir)
        install_adapter_config_shim()
        try:
            return initialize_adapter_from_environment(), "robocorp-adapters-custom"
        except RuntimeError:
            raise
        except Exception as exc:
            return InMemoryWorkItemAdapter(), f"in-memory-fallback:{type(exc).__name__}"
    return InMemoryWorkItemAdapter(), "in-memory"


def run_smoke_sqlite_workitem_flow(
    *,
    adapter=None,
    output_dir: Optional[Path] = None,
    prefer_real_adapter: bool = True,
) -> JSONDict:
    artifacts_dir = resolve_output_dir(output_dir)
    selected_adapter, adapter_kind = (
        (adapter, "provided") if adapter is not None else make_smoke_adapter(artifacts_dir, prefer_real=prefer_real_adapter)
    )
    queue = WorkItemQueue(selected_adapter)

    input_id = queue.enqueue_input(build_synthetic_payload())
    result = CodexWorkItemWorker(queue=queue, runner=harmless_runner).work_one()

    output_payload: JSONDict = {}
    if result.output_id:
        try:
            output_payload = selected_adapter.load_payload(result.output_id)
        except Exception:
            outputs = getattr(selected_adapter, "outputs", {})
            output_payload = outputs.get(result.output_id, {})
    proof: JSONDict = {
        "status": "PASS" if result.succeeded else "FAIL",
        "adapter": adapter_kind,
        "input_id": input_id,
        "worker": {
            "item_id": result.item_id,
            "output_id": result.output_id,
            "succeeded": result.succeeded,
        },
        "output_payload": output_payload,
        "safe_by_default": True,
        "mutated_fizzy": False,
    }

    proof_path = artifacts_dir / "smoke-workitem-flow.json"
    proof_path.write_text(json.dumps(proof, indent=2, sort_keys=True), encoding="utf-8")
    proof["proof_path"] = str(proof_path)
    return proof


@task
def Doctor() -> None:
    output_dir = resolve_output_dir()
    result = {
        "robot": "fizzy-symphony-workitems",
        "output_dir": str(output_dir),
        "adapter_package_available": adapter_package_available(),
        "safe_by_default": True,
    }
    print(json.dumps(result, indent=2, sort_keys=True))


@task
def WorkitemsEnv() -> None:
    print(format_workitem_env(RobocorpWorkitemConfig()))


@task
def SmokeSQLiteWorkitemFlow() -> None:
    proof = run_smoke_sqlite_workitem_flow()
    print(json.dumps(proof, indent=2, sort_keys=True))
