---
name: RCC workai_production_smoke

"on":
  workflow_dispatch:

jobs:
  workai-production-smoke:
    uses: ./.github/workflows/_rcc-robot.yml
    secrets: inherit
    with:
      suite: workai_production_smoke
      task: WorkAIProductionSmoke
